const CarfilterApi = [
    {
        // name:"",
        package:"Normal",
        catagory:"sedan",
        price:"5999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
    },
    {
        package:"Golden",
        catagory:"sedan",
        price:"9999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
        data13:" Machine Paint Polishing ",
        data14:"Clay Treatment",
        data15:"LimeScale Removal",
        data16:"Machine Paint Compounding",
    },
    {
        package:"Normal",
        catagory:"luxurysedan",
        price:"7999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
    },
    {
        package:"Golden",
        catagory:"luxurysedan",
        price:"12999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
        data13:" Machine Paint Polishing ",
        data14:"Clay Treatment",
        data15:"LimeScale Removal",
        data16:"Machine Paint Compounding",
    },

    {
        package:"Normal",
        catagory:"suv",
        price:"10999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
    },
    {
        package:"Golden",
        catagory:"suv",
        price:"15999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
        data13:" Machine Paint Polishing ",
        data14:"Clay Treatment",
        data15:"LimeScale Removal",
        data16:"Machine Paint Compounding",
    },
    {
        package:"Normal",
        catagory:"hatchback",
        price:"3999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
    },
    {
        package:"Golden",
        catagory:"hatchback",
        price:"6999",
        data1:"  Jet Foam Wash ",
        data2:"Rim Extensive Cleaning",
        data3:"Wheel Arches/Wells Cleaning",
        data4:"Door Jams Cleaning",
        data5:"Odor Elimination",
        data6:"Mats Foam Wash",
        data7:"Dashboard Cleaning & Reconditioning",
        data8:"Upholstery/Seats Cleaning",
        data9:"Leather Seats/Dash Lining",
        data10:"Interior Spot Removal",
        data11:"Headliner Cleaning",
        data12:" Engine Degreasing and Dressing",
        data13:" Machine Paint Polishing ",
        data14:"Clay Treatment",
        data15:"LimeScale Removal",
        data16:"Machine Paint Compounding",
    },
]
module.exports = CarfilterApi